import uuid
from dataclasses import dataclass, asdict, field
from datetime import datetime
from typing import List, Dict, Any, Optional
from signals.core.enums import Market, SignalCategory
from .enums import ActionType, OutcomeType

@dataclass(frozen=True)
class Strategy:
    """
    Declarative strategy definition.
    """
    strategy_id: str
    strategy_name: str
    market_scope: Market
    
    # Eligibility
    eligible_categories: List[SignalCategory]
    min_confidence: float
    
    # Rules (Textual for now, can be parsed later)
    entry_rules: str
    exit_rules: str
    max_holding_period_hours: int
    
    # Risk
    max_position_pct: float # e.g., 0.05 for 5%
    
    created_at: datetime
    version: int

    @classmethod
    def create(cls, name: str, market: Market, cats: List[SignalCategory], 
               min_conf: float, entry: str, exit_r: str, 
               hold_hrs: int, pos_pct: float) -> 'Strategy':
        return cls(
            strategy_id=str(uuid.uuid4()),
            strategy_name=name,
            market_scope=market,
            eligible_categories=cats,
            min_confidence=min_conf,
            entry_rules=entry,
            exit_rules=exit_r,
            max_holding_period_hours=hold_hrs,
            max_position_pct=pos_pct,
            created_at=datetime.utcnow(),
            version=1
        )

@dataclass(frozen=True)
class PaperAction:
    """
    A hypothetical action generated by the sandbox.
    """
    action_id: str
    strategy_id: str
    action_type: ActionType
    timestamp: datetime
    
    # Context
    asset_id: str
    supporting_signal_ids: List[str]
    supporting_narrative_ids: List[str]
    confidence_snapshot: float
    
    # Reasoning
    reasoning_payload: Dict[str, Any]

@dataclass(frozen=True)
class PaperOutcome:
    """
    Result of a paper trade.
    """
    outcome_id: str
    action_id: str
    
    entry_price: float
    exit_price: float
    pnl_pct: float
    
    directional_correct: bool
    holding_hours: float
    outcome_type: OutcomeType
    
    # Audit
    evaluated_at: datetime
