import React, { useEffect, useState } from 'react';
import {
  getPortfolioAdvisory,
  getCombinedPortfolio,
  getPortfolioDiversification,
  getPortfolioExposure,
  getPortfolioHoldings,
  getPortfolioInsights,
  getPortfolioMacroAlignment,
  getPortfolioOverview,
  getPortfolioRefreshStatus,
  getPortfolioTrend,
  getPortfolioResearch,
  getPortfolioResilience,
  getPortfolioRisk,
  triggerPortfolioRefresh,
} from '../services/portfolioApi';
import MutualFundIntelligencePanel from './MutualFundIntelligencePanel';
import LookthroughCoveragePanel from './LookthroughCoveragePanel';
import PortfolioEventIntelligencePanel from './PortfolioEventIntelligencePanel';
import PortfolioExposurePanel from './PortfolioExposurePanel';
import PortfolioRefreshControl from './PortfolioRefreshControl';
import PortfolioRiskAlertsPanel from './PortfolioRiskAlertsPanel';
import PortfolioSuggestionsPanel from './PortfolioSuggestionsPanel';
import PortfolioStrategySummaryPanel from './PortfolioStrategySummaryPanel';
import PortfolioTrendPanel from './PortfolioTrendPanel';
import StockResearchPanel from './StockResearchPanel';
import OpportunitySignalsPanel from './OpportunitySignalsPanel';
import ValuationOverviewPanel from './ValuationOverviewPanel';
import './PortfolioExposurePanel.css';
import './PortfolioIntelligencePanel.css';

/* ── Metric Definitions ─────────────────────────────────────────────────── */
const METRIC_DEFS = {
  resilience: {
    label: 'Resilience Score',
    short: 'Ability to withstand macro and market shocks.',
    guide: '< 0.4 fragile · 0.4–0.7 adequate · > 0.7 strong',
  },
  concentration: {
    label: 'Concentration Score',
    short: 'How concentrated the portfolio is in a few holdings.',
    guide: 'Lower = more concentrated. Higher = better diversified.',
  },
  macroSensitivity: {
    label: 'Macro Sensitivity',
    short: 'Sensitivity to macro regime changes (rates, inflation, liquidity).',
    guide: 'Higher value = more exposed to macro shocks.',
  },
  regimeAlignment: {
    label: 'Regime Alignment',
    short: 'How well portfolio exposures match the current macro regime.',
    guide: 'Higher = better aligned with current conditions.',
  },
  diversification: {
    label: 'Diversification',
    short: 'Spread of holdings across sectors and industries.',
    guide: '1.0 = perfectly diversified · 0.0 = single-sector.',
  },
  factorBalance: {
    label: 'Factor Balance',
    short: 'Evenness of portfolio factor exposure distribution.',
    guide: 'Higher = more balanced across growth, value, momentum, quality.',
  },
  mutualFundSupport: {
    label: 'Mutual Fund Support',
    short: 'How much the mutual fund sleeve improves or weakens resilience through ballast, diversification, or concentration.',
    guide: 'Higher = more supportive fund sleeve. Lower = concentrated or thematic fund risk dominates.',
  },
  equitySleeveResilience: {
    label: 'Equity Sleeve Resilience',
    short: 'Resilience of the direct equity sleeve before blending with the mutual fund sleeve.',
    guide: 'Derived from diversification, concentration, regime alignment, and momentum health of direct holdings.',
  },
  fundSleeveResilience: {
    label: 'Fund Sleeve Resilience',
    short: 'Resilience support generated by the mutual fund sleeve.',
    guide: 'Higher = stronger ballast/diversification support. Lower = thematic or concentrated fund sleeve risk.',
  },
  blendedContribution: {
    label: 'Blended Contribution',
    short: 'Allocation-weighted contribution of each sleeve to the final resilience score.',
    guide: 'Final resilience = equity contribution + fund contribution.',
  },
  compositeHealth: {
    label: 'Composite Health',
    short: 'Overall portfolio health — average of all exposure scores.',
    guide: '> 0.7 strong · 0.4–0.7 adequate · < 0.4 fragile',
  },
};

const Tooltip = ({ def }) => {
  const [open, setOpen] = useState(false);
  if (!def) return null;
  return (
    <span
      className="metric-tooltip-trigger"
      onMouseEnter={() => setOpen(true)}
      onMouseLeave={() => setOpen(false)}
    >
      ⓘ
      {open && (
        <span className="metric-tooltip-popup">
          <strong>{def.label}</strong>
          <span>{def.short}</span>
          <em>{def.guide}</em>
        </span>
      )}
    </span>
  );
};

/* ── Helpers ──────────────────────────────────────────────────────────── */
const formatTimestamp = (ts) => {
  if (!ts) return 'UNAVAILABLE';
  try {
    const d = new Date(ts);
    return d.toLocaleString();
  } catch {
    return ts;
  }
};

const classifyScore = (score) => {
  if (score == null) return '';
  if (score >= 0.7) return 'strong';
  if (score >= 0.4) return 'adequate';
  return 'fragile';
};

/* ── Raw Data Trace Panel ─────────────────────────────────────────────── */
const RawDataTracePanel = ({ holdings, selectedPortfolioId, market }) => {
  const [expanded, setExpanded] = useState(false);
  if (!holdings) return null;

  const trace = holdings.trace || {};
  const refreshDiag = holdings.refresh_diagnostics || {};
  const summary = holdings.portfolio_summary || {};

  return (
    <div className="raw-trace-panel">
      <button className="raw-trace-toggle" onClick={() => setExpanded(!expanded)}>
        {expanded ? '▾' : '▸'} Raw Data Traceability
      </button>
      {expanded && (
        <div className="raw-trace-content">
          <div className="raw-trace-section">
            <h5>Data Artifact Paths</h5>
            <div className="breakdown-list">
              <div className="breakdown-row">
                <span>Analytics Source</span>
                <span className="trace-path">{trace.source || `data/portfolio_intelligence/analytics/${market}/${selectedPortfolioId}/latest.json`}</span>
              </div>
              <div className="breakdown-row">
                <span>Normalized Source</span>
                <span className="trace-path">{`data/portfolio_intelligence/normalized/${market}/${selectedPortfolioId}/latest.json`}</span>
              </div>
              <div className="breakdown-row">
                <span>Raw Import</span>
                <span className="trace-path">{`data/portfolio_intelligence/imports/${market}/${selectedPortfolioId}/latest.json`}</span>
              </div>
            </div>
          </div>
          <div className="raw-trace-section">
            <h5>Ingestion Diagnostics</h5>
            <div className="breakdown-list">
              <div className="breakdown-row">
                <span>Analytics Engine</span>
                <span>{trace.analytics_engine || 'portfolio_intelligence.analytics'}</span>
              </div>
              <div className="breakdown-row">
                <span>Data Source</span>
                <span>{trace.data_source || holdings.portfolio_data_source || 'UNAVAILABLE'}</span>
              </div>
              <div className="breakdown-row">
                <span>Source Provenance</span>
                <span>{trace.source_provenance || holdings.source_provenance || 'UNAVAILABLE'}</span>
              </div>
              <div className="breakdown-row">
                <span>Ingestion Timestamp</span>
                <span>{formatTimestamp(refreshDiag.ingested_at)}</span>
              </div>
              <div className="breakdown-row">
                <span>Connector Mode</span>
                <span>{refreshDiag.connector_mode || 'UNAVAILABLE'}</span>
              </div>
            </div>
          </div>
          {Object.keys(summary).length > 0 && (
            <div className="raw-trace-section">
              <h5>Broker Portfolio Summary</h5>
              <div className="breakdown-list">
                {Object.entries(summary).slice(0, 8).map(([k, v]) => (
                  <div className="breakdown-row" key={k}>
                    <span>{k}</span>
                    <span>{typeof v === 'object' ? JSON.stringify(v) : String(v)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

const PortfolioIntelligencePanel = ({ market }) => {
  const [overview, setOverview] = useState(null);
  const [selectedPortfolioId, setSelectedPortfolioId] = useState(null);
  const [holdings, setHoldings] = useState(null);
  const [diversification, setDiversification] = useState(null);
  const [risk, setRisk] = useState(null);
  const [insights, setInsights] = useState(null);
  const [resilience, setResilience] = useState(null);
  const [exposure, setExposure] = useState(null);
  const [macroAlignment, setMacroAlignment] = useState(null);
  const [research, setResearch] = useState(null);
  const [advisory, setAdvisory] = useState(null);
  const [refreshStatus, setRefreshStatus] = useState(null);
  const [trend, setTrend] = useState(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [combined, setCombined] = useState(null);
  const [error, setError] = useState(null);

  const loadPortfolioDetails = (portfolioId) => Promise.all([
    getPortfolioHoldings(market, portfolioId),
    getPortfolioDiversification(market, portfolioId),
    getPortfolioRisk(market, portfolioId),
    getPortfolioInsights(market, portfolioId),
    getPortfolioResilience(market, portfolioId),
    getPortfolioExposure(market, portfolioId),
    getPortfolioMacroAlignment(market, portfolioId),
    getPortfolioResearch(market, portfolioId),
    getPortfolioAdvisory(market, portfolioId),
    getPortfolioRefreshStatus(market, portfolioId),
    getPortfolioTrend(market, portfolioId),
  ]).then(([
    holdingsPayload,
    diversificationPayload,
    riskPayload,
    insightsPayload,
    resiliencePayload,
    exposurePayload,
    macroPayload,
    researchPayload,
    advisoryPayload,
    refreshStatusPayload,
    trendPayload,
  ]) => {
    setHoldings(holdingsPayload);
    setDiversification(diversificationPayload);
    setRisk(riskPayload);
    setInsights(insightsPayload);
    setResilience(resiliencePayload);
    setExposure(exposurePayload);
    setMacroAlignment(macroPayload);
    setResearch(researchPayload);
    setAdvisory(advisoryPayload);
    setRefreshStatus(refreshStatusPayload);
    setTrend(trendPayload);
  });

  useEffect(() => {
    setError(null);
    setOverview(null);
    setHoldings(null);
    setDiversification(null);
    setRisk(null);
    setInsights(null);
    setResilience(null);
    setExposure(null);
    setMacroAlignment(null);
    setResearch(null);
    setAdvisory(null);
    setRefreshStatus(null);
    setTrend(null);
    Promise.all([
      getPortfolioOverview(market),
      getCombinedPortfolio(),
    ])
      .then(([overviewPayload, combinedPayload]) => {
        setOverview(overviewPayload);
        setCombined(combinedPayload);
        const firstPortfolio = overviewPayload?.portfolios?.[0]?.portfolio_id || null;
        setSelectedPortfolioId(firstPortfolio);
      })
      .catch((err) => {
        console.error(err);
        setError(err.message);
      });
  }, [market]);

  useEffect(() => {
    if (!selectedPortfolioId) {
      return;
    }
    loadPortfolioDetails(selectedPortfolioId)
      .catch((err) => {
        console.error(err);
        setError(err.message);
      });
  }, [market, selectedPortfolioId]);

  const handleRefresh = async (options = {}) => {
    if (!selectedPortfolioId) return;
    setIsRefreshing(true);
    setError(null);
    try {
      await triggerPortfolioRefresh(market, selectedPortfolioId, {
        account_name: selectedPortfolio?.display_name || selectedPortfolio?.account_name || 'Zerodha Primary',
        ...options,
      });
      const [overviewPayload, combinedPayload] = await Promise.all([
        getPortfolioOverview(market),
        getCombinedPortfolio(),
      ]);
      setOverview(overviewPayload);
      setCombined(combinedPayload);
      await loadPortfolioDetails(selectedPortfolioId);
    } catch (err) {
      console.error(err);
      setError(err.message);
    } finally {
      setIsRefreshing(false);
    }
  };

  const portfolios = overview?.portfolios || [];
  const selectedPortfolio = portfolios.find((portfolio) => portfolio.portfolio_id === selectedPortfolioId) || portfolios[0] || null;
  const topHoldings = [...(holdings?.holdings || [])].sort((a, b) => (b.weight_pct || 0) - (a.weight_pct || 0)).slice(0, 8);
  const mutualFundHoldings = [...(holdings?.mutual_fund_holdings || [])].sort((a, b) => (b.weight_pct || 0) - (a.weight_pct || 0)).slice(0, 8);
  const insightRows = insights?.insights?.slice(0, 6) || [];
  const sectorBreakdown = diversification?.diversification?.sector_allocation || {};
  const factorBreakdown = diversification?.diversification?.factor_distribution || {};
  const portfolioDataSource = holdings?.portfolio_data_source || selectedPortfolio?.portfolio_data_source || 'UNAVAILABLE';
  const diagnostics = holdings?.refresh_diagnostics || selectedPortfolio?.refresh_diagnostics || {};
  const mcpDiagnostics = diagnostics?.mcp || {};
  const apiFallback = diagnostics?.api_fallback || {};
  const portfolioSuggestions = advisory?.portfolio_suggestions || [];
  const portfolioRiskAlerts = advisory?.portfolio_risk_alerts || [];
  const portfolioStrategySummary = advisory?.portfolio_strategy_summary || {};
  const portfolioStrengtheningInsights = advisory?.portfolio_strengthening_insights || [];
  const portfolioOpportunitySignals = advisory?.portfolio_opportunity_signals || [];
  const researchNarrative = advisory?.research_synthesis || research?.research_synthesis || {};
  const stockResearchProfiles = research?.stock_research_profiles || [];
  const stockSummaries = research?.stock_intelligence_summaries || [];
  const mutualFundIntelligence = research?.mutual_fund_intelligence || {};
  const valuationOverview = research?.valuation_overview || {};
  const portfolioEventAlerts = research?.portfolio_event_alerts || advisory?.portfolio_event_alerts || [];
  const portfolioEventTimeline = research?.portfolio_event_timeline || [];
  const newsAdapterStatus = research?.news_adapter_status || advisory?.news_adapter_status || {};

  return (
    <section className="portfolio-intelligence-panel">
      <div className="portfolio-intel-header">
        <div>
          <h3>Portfolio Intelligence</h3>
          <p>Read-only broker portfolio analytics with provenance and regime gating.</p>
        </div>
        <div className="portfolio-trace-block">
          <div className="portfolio-trace">
            <span>Epoch: {overview?.truth_epoch || 'TRUTH_EPOCH_2026-03-06_01'}</span>
            <span>Scope: {market}</span>
            <span>Source: {portfolioDataSource}</span>
          </div>
          <PortfolioRefreshControl refreshStatus={refreshStatus} onRefresh={handleRefresh} isRefreshing={isRefreshing} />
        </div>
      </div>

      {error && <div className="portfolio-error">Portfolio intelligence unavailable: {error}</div>}

      {!error && portfolios.length === 0 && (
        <div className="portfolio-empty">
          <strong>No imported portfolios available for {market}.</strong>
          <span>Run the read-only tracker refresh outside the dashboard to populate analytics artifacts.</span>
        </div>
      )}

      {portfolios.length > 0 && (
        <>
          <div className="portfolio-overview-grid">
            <div className="portfolio-metric">
              <span>Total Value</span>
              <strong>{overview?.aggregated?.total_value?.toLocaleString?.() ?? overview?.aggregated?.total_value}</strong>
            </div>
            <div className="portfolio-metric">
              <span>Total PnL</span>
              <strong>{overview?.aggregated?.total_pnl?.toLocaleString?.() ?? overview?.aggregated?.total_pnl}</strong>
            </div>
            <div className="portfolio-metric">
              <span>Positions</span>
              <strong>{overview?.aggregated?.total_positions}</strong>
            </div>
            <div className="portfolio-metric">
              <span>Resilience <Tooltip def={METRIC_DEFS.resilience} /></span>
              <strong className={`score-${classifyScore(overview?.aggregated?.resilience_score)}`}>
                {overview?.aggregated?.resilience_score} {overview?.aggregated?.resilience_classification}
              </strong>
              <em className="metric-status">{classifyScore(overview?.aggregated?.resilience_score)}</em>
            </div>
          </div>

          <div className="portfolio-selector-row">
            {portfolios.map((portfolio) => (
              <button
                key={portfolio.portfolio_id}
                className={portfolio.portfolio_id === selectedPortfolioId ? 'active' : ''}
                onClick={() => setSelectedPortfolioId(portfolio.portfolio_id)}
              >
                {portfolio.display_name} [{portfolio.broker}]
              </button>
            ))}
          </div>

          <div className="portfolio-intel-grid">
            <div className="portfolio-card">
              <h4>Top Holdings</h4>
              <div className="portfolio-table">
                <div className="portfolio-table-header">
                  <span>Symbol</span>
                  <span>Weight</span>
                  <span>Conviction</span>
                  <span>Flags</span>
                </div>
                {topHoldings.map((item) => (
                  <div className="portfolio-table-row" key={`${item.ticker}-${item.asset_bucket || 'row'}`}>
                    <span>{item.ticker}</span>
                    <span>{item.weight_pct}%</span>
                    <span>{item.conviction_score}</span>
                    <span>{item.risk_flags?.join(', ') || 'NONE'}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="portfolio-card">
              <h4>Diversification</h4>
              <div className="breakdown-list">
                {Object.entries(sectorBreakdown).map(([key, value]) => (
                  <div key={key} className="breakdown-row">
                    <span>{key}</span>
                    <span>{value}%</span>
                  </div>
                ))}
              </div>
              <h5>Factor Exposure</h5>
              <div className="breakdown-list">
                {Object.entries(factorBreakdown).map(([key, value]) => (
                  <div key={key} className="breakdown-row">
                    <span>{key}</span>
                    <span>{value}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="portfolio-card">
              <h4>Mutual Fund Holdings</h4>
              <div className="portfolio-table">
                <div className="portfolio-table-header">
                  <span>Fund</span>
                  <span>Weight</span>
                  <span>Value</span>
                  <span>PnL</span>
                </div>
                {mutualFundHoldings.length === 0 && (
                  <div className="portfolio-table-row">
                    <span>None</span>
                    <span>-</span>
                    <span>-</span>
                    <span>-</span>
                  </div>
                )}
                {mutualFundHoldings.map((item) => (
                  <div className="portfolio-table-row" key={`${item.ticker}-${item.asset_bucket || 'mf'}`}>
                    <span>{item.security_name || item.ticker}</span>
                    <span>{item.weight_pct}%</span>
                    <span>{item.market_value}</span>
                    <span>{item.pnl}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="portfolio-card">
              <h4>Risk and Resilience</h4>
              <div className="breakdown-list">
                <div className="breakdown-row">
                  <span>Regime Gate</span>
                  <span>{risk?.regime_gate_state || holdings?.regime_gate_state}</span>
                </div>
                <div className="breakdown-row">
                  <span>Concentration Score <Tooltip def={METRIC_DEFS.concentration} /></span>
                  <span>{risk?.risk?.concentration_score}</span>
                </div>
                <div className="breakdown-row">
                  <span>Macro Sensitivity <Tooltip def={METRIC_DEFS.macroSensitivity} /></span>
                  <span>{risk?.risk?.macro_sensitivity}</span>
                </div>
                <div className="breakdown-row">
                  <span>Resilience <Tooltip def={METRIC_DEFS.resilience} /></span>
                  <span className={`score-${classifyScore(resilience?.resilience?.overall_score)}`}>
                    {resilience?.resilience?.overall_score} {resilience?.resilience?.classification}
                  </span>
                </div>
                <div className="breakdown-row">
                  <span>Equity Sleeve <Tooltip def={METRIC_DEFS.equitySleeveResilience} /></span>
                  <span>{resilience?.resilience?.components?.equity_sleeve_resilience ?? 'N/A'}</span>
                </div>
                <div className="breakdown-row">
                  <span>Mutual Fund Support <Tooltip def={METRIC_DEFS.mutualFundSupport} /></span>
                  <span>{resilience?.resilience?.components?.mutual_fund_support ?? 'N/A'}</span>
                </div>
                <div className="breakdown-row">
                  <span>Fund Sleeve <Tooltip def={METRIC_DEFS.fundSleeveResilience} /></span>
                  <span>{resilience?.resilience?.components?.mutual_fund_sleeve_resilience ?? 'N/A'}</span>
                </div>
                <div className="breakdown-row strategy-summary-row">
                  <span>Blend Weights</span>
                  <span>
                    Equity {resilience?.resilience?.components?.equity_allocation_weight ?? 0}
                    {' / '}
                    Funds {resilience?.resilience?.components?.mutual_fund_allocation_weight ?? 0}
                  </span>
                </div>
                <div className="breakdown-row strategy-summary-row">
                  <span>Blend Contribution <Tooltip def={METRIC_DEFS.blendedContribution} /></span>
                  <span>
                    Equity {resilience?.resilience?.components?.equity_resilience_contribution ?? 0}
                    {' / '}
                    Funds {resilience?.resilience?.components?.mutual_fund_resilience_contribution ?? 0}
                  </span>
                </div>
              </div>
            </div>

            <div className="portfolio-card">
              <h4>Data Provenance and Freshness</h4>
              <div className="breakdown-list">
                <div className="breakdown-row">
                  <span>Data Source</span>
                  <span className={`source-badge source-${portfolioDataSource.toLowerCase()}`}>{portfolioDataSource}</span>
                </div>
                <div className="breakdown-row">
                  <span>Portfolio Last Refresh</span>
                  <span>{formatTimestamp(holdings?.portfolio_refresh_timestamp || selectedPortfolio?.portfolio_refresh_timestamp)}</span>
                </div>
                <div className="breakdown-row">
                  <span>Market Data Timestamp</span>
                  <span>{formatTimestamp(holdings?.data_as_of || selectedPortfolio?.last_updated)}</span>
                </div>
                <div className="breakdown-row">
                  <span>Truth Epoch</span>
                  <span>{holdings?.truth_epoch || overview?.truth_epoch || 'TRUTH_EPOCH_2026-03-06_01'}</span>
                </div>
                <div className="breakdown-row provenance-note">
                  <span colSpan="2">Truth epoch = system knowledge baseline. Refresh timestamp = latest portfolio snapshot.</span>
                </div>
              </div>
              <h5>Broker Connectivity</h5>
              <div className="breakdown-list">
                <div className="breakdown-row">
                  <span>Broker Status</span>
                  <span>{diagnostics?.broker_connectivity || 'UNAVAILABLE'}</span>
                </div>
                <div className="breakdown-row">
                  <span>MCP Status</span>
                  <span>{mcpDiagnostics?.portfolio_fetch_status || mcpDiagnostics?.connectivity_status || 'UNAVAILABLE'}</span>
                </div>
                <div className="breakdown-row">
                  <span>API Fallback</span>
                  <span>{apiFallback?.status || 'UNAVAILABLE'}</span>
                </div>
                <div className="breakdown-row">
                  <span>Source Provenance</span>
                  <span>{holdings?.source_provenance || 'UNAVAILABLE'}</span>
                </div>
              </div>
            </div>

            <div className="portfolio-card">
              <h4>Insights</h4>
              <div className="insight-list">
                {insightRows.map((item, index) => (
                  <div className={`insight-item ${item.severity?.toLowerCase() || 'info'}`} key={`${item.category}-${index}`}>
                    <strong>{item.headline}</strong>
                    <span>{item.detail}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <PortfolioExposurePanel exposure={exposure} macroAlignment={macroAlignment} metricDefs={METRIC_DEFS} />

          <div className="portfolio-intel-grid portfolio-intel-grid-expanded">
            <PortfolioStrategySummaryPanel summary={portfolioStrategySummary} strengtheningInsights={portfolioStrengtheningInsights} />
            <PortfolioRiskAlertsPanel alerts={portfolioRiskAlerts} />
            <PortfolioSuggestionsPanel suggestions={portfolioSuggestions} synthesis={researchNarrative} />
            <OpportunitySignalsPanel signals={portfolioOpportunitySignals} />
            <PortfolioEventIntelligencePanel
              adapterStatus={newsAdapterStatus}
              alerts={portfolioEventAlerts}
              timeline={portfolioEventTimeline}
            />
            <LookthroughCoveragePanel funds={holdings?.mutual_fund_holdings || []} />
            <MutualFundIntelligencePanel intelligence={mutualFundIntelligence} />
            <PortfolioTrendPanel trend={trend} />
            <ValuationOverviewPanel valuationOverview={valuationOverview} />
            <StockResearchPanel profiles={stockResearchProfiles} summaries={stockSummaries} />
          </div>

          <RawDataTracePanel holdings={holdings} selectedPortfolioId={selectedPortfolioId} market={market} />

          <div className="portfolio-combined-bar">
            <span>Combined US Value: {combined?.us_portfolio_value ?? 0}</span>
            <span>Combined India Value: {combined?.india_portfolio_value ?? 0}</span>
            <span>Combined USD: {combined?.combined_value_usd ?? 'BLOCKED'}</span>
            <span>FX Source: {combined?.fx_source}</span>
          </div>
        </>
      )}
    </section>
  );
};

export default PortfolioIntelligencePanel;
