from enum import Enum, unique

@unique
class RecommendationType(str, Enum):
    MONITOR_CLOSELY = "MONITOR_CLOSELY"
    REGIME_RESTRICTION_SUGGESTED = "REGIME_RESTRICTION_SUGGESTED"
    CONFIDENCE_RECALIBRATION_NEEDED = "CONFIDENCE_RECALIBRATION_NEEDED"
    REDESIGN_CANDIDATE = "REDESIGN_CANDIDATE"
    DEPRECATION_CANDIDATE = "DEPRECATION_CANDIDATE"
    NO_ACTION = "NO_ACTION"

@unique
class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
