import uuid
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Dict, Any

@dataclass(frozen=True)
class NarrativeSummary:
    """
    Human-readable presentation of a Narrative.
    Generated by LLM (or deterministic templates).
    """
    summary_id: str
    narrative_id: str
    
    # Content
    headline: str
    summary_text: str
    key_points: str # Bullet points, newline separated
    
    # Metadata
    summary_confidence: float # Derived from Narrative + Gen Model confidence
    generated_at: datetime
    model_metadata: Dict[str, Any] # e.g. {"model": "gpt-4", "template_version": "1.0"}
    
    version: int
    
    @classmethod
    def create(cls, narrative_id: str, headline: str, text: str, points: str, confidence: float, metadata: Dict) -> 'NarrativeSummary':
        return cls(
            summary_id=str(uuid.uuid4()),
            narrative_id=narrative_id,
            headline=headline,
            summary_text=text,
            key_points=points,
            summary_confidence=confidence,
            generated_at=datetime.utcnow(),
            model_metadata=metadata,
            version=1
        )

    def to_dict(self):
        d = asdict(self)
        if d.get('generated_at'):
            d['generated_at'] = d['generated_at'].isoformat()
        return d

    @staticmethod
    def from_dict(d: Dict) -> 'NarrativeSummary':
        if d.get('generated_at'):
            d['generated_at'] = datetime.fromisoformat(d['generated_at'])
        return NarrativeSummary(**d)
