from abc import ABC, abstractmethod
from typing import Dict, Any, Tuple
from pathlib import Path

class BaseExecutor(ABC):
    """
    Abstract base class for all execution backends.
    Renamed from Executor to BaseExecutor for legacy compatibility.
    """
    def __init__(self, project_root: Path):
        self.project_root = project_root
    
    @property
    def name(self) -> str:
        """Return the unique name of the executor (e.g. ANTIGRAVITY, JULES, GEMINI)."""
        return "LEGACY_EXECUTOR"

    def is_available(self) -> bool:
        """
        Check if the executor is available for use.
        Returns True if all dependencies and auth checks pass.
        """
        return True

    @abstractmethod
    def execute(self, action_plan: Dict[str, Any], *args, **kwargs) -> Tuple[str, str]:
        """
        Execute the given action plan.
        
        Args:
            action_plan: The parsed action_plan.json content.
            *args, **kwargs: Allow extra args for legacy compatibility (e.g. run_dir).
            
        Returns:
            Tuple[str, str]: (diff_output, log_output)
            - diff_output: The unified diff string generated by the execution.
            - log_output: A human-readable log or summary of the execution.
            
        Raises:
            RuntimeError: If execution fails abruptly.
        """
        pass

# Alias for new code
Executor = BaseExecutor
