# Database connection config
# The ingest script will use the provided `url` if present. Otherwise it will
# fall back to constructing a PostgreSQL connection string using the remaining
# fields.
url: sqlite:///nse_data.db
# host: localhost
# database: nse_data
# user: postgres
# password: 'Betsson@11'
# port: 5432
